### ISSUE TITLE
Email domain

### ISSUE THREAD

**Issue by billy-boatright** [custodietmssp/Custodiet#2]
Should we have a single domain?

**Comment by dlseyer** [comment]
do you mean register a new domain that we can use for e-mail?

**Comment by billy-boatright** [comment]
Yes, because I don't have a lot of experience changing the config 
files.  I've had to reinstall SO 3 or 4 times because I messed up 
somewhere.  Whereas, if we had one email domain, doesn't matter which 
(Joshua's, mine, gmail), we could have 3 identical box configurations.  
In addition, we're going to want one email domain for the potential SOC.

I more brought it up, because I was having trouble with the config files 
in all the different programs

**Comment by dlseyer** [comment]
how about this:
- your create an e-mail account like "smbbox@gmail.com" if that is available, or something similar if not
- we agree on a secure password for the account
- you use that e-mail address for your configuration

Would that get you past your current issue? In other words, have I correctly understood the issue?

**Comment by jmarpet** [comment]
ok, Good idea.  We can use my current domain, Guardedrisk.com, or I can
register a new one for our test systems.  Why don't I do that.  Tell you
what, I own Psychosecurity.com.  Let's use that. Billy, I'll give you creds
for it on Godaddy (my registrar), and you can manage the domain.  Is that
ok?  That way, if we need DNS changes, we're good.

On Mon, Sep 16, 2013 at 10:59 AM, billy-boatright
notifications@github.comwrote:

> Yes, because I don't have a lot of experience changing the config
> files. I've had to reinstall SO 3 or 4 times because I messed up
> somewhere. Whereas, if we had one email domain, doesn't matter which
> (Joshua's, mine, gmail), we could have 3 identical box configurations.
> In addition, we're going to want one email domain for the potential SOC.
> 
> I more brought it up, because I was having trouble with the config files
> in all the different programs
> 
> On 9/16/13 6:25 AM, dlseyer wrote:
> 
> > do you mean register a new domain that we can use for e-mail?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jmarpet/SMB-Box/issues/2#issuecomment-24509218.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jmarpet/SMB-Box/issues/2#issuecomment-24516270
> .

## 

_Joshua A. Marpet_

Managing Principal

_GuardedRisk_

**

_Before the Breach *_and *_After The Incident!_

*
*

1-855-23G-RISK (855-234-7475)

Cell: (908) 916-7764

Joshua.Marpet@guardedrisk.com

http://www.GuardedRisk.com

---

_This communication (including any attachments) contains privileged and
confidential information from GuardedRisk which is intended for a specific
individual and purpose, and is protected by law.  If you are not the
intended recipient, you may not read, copy, distribute, or use this
information, and no privilege has been waived by your inadvertent receipt.
Furthermore, you should delete this communication and / or shred the
materials and any attachments and are hereby notified that any disclosure,
copying, or distribution of this communication, or the taking of any action
based on it, is strictly prohibited._

**Comment by billy-boatright** [comment]
Sir, you are a genius. 

That is exactly what I meant. 

Thank you,
Billy
