### ISSUE TITLE
Proposed Git Reflow.

### ISSUE THREAD

**Issue by RevREB** [custodietmssp/Custodiet#7]
Long run branches:
- master
- release
- devel (devel is head)

devel will branch short term based on milestone's
milestone's will get branched for specific feature request/issue's

Forks and Pulls requests should go against the devel branch

**Comment by databeast** [comment]
I'm thinking permanent milestone branches (well, as long as the milestone is active)

pullreqs are made to that milestone branch. if we're happy, we merge the milestone (once completed) into dev.

**Comment by RevREB** [comment]
Right thats why they are short term branches. The Milestone branches should collapse after that milestone is completed and merged.

**Comment by Dr-Syn** [comment]
I concur with @RevREB - it would make things 'neater' if milestones collapse into the main branches when they're finished.
